notifications:
    email: false # turn off email notifications for build failure

sudo: required

env:
    - distribution: ubuntu
      version: 16.04
      services:
          - docker

    - distribution: ubuntu
      version: 14.04
      services:
          - docker

    # Default environment of MacOS El Capitan
    # compiled using clang shipped with xcode8
    - os: osx
      osx_image: xcode8

    # Default environment of MacOS Sierra
    # compiled using clang shipped with xcode8.3
    - os: osx
      osx_image: xcode8.3

language: c++

compiler:
    - gcc

before_install:

    # Ubuntu systems Docker as travis-ci supports up to ubuntu 14.04.
    # pull and running docker on the background
    # installing dependencies. install sudo as it is not installed by default.
    # Note: Ubuntu 14.04 and this environment does not recognize sudo apt-get install libglfw3-dev
    # Comment in if-statement is now allowed.
    -   if [ "$distribution" == "ubuntu" ]; then
            docker pull ${distribution}:${version};
            docker run -d -v $(pwd):/travis_ci ${distribution}:${version} /bin/bash -c 'while true; do sleep 1; done';
            docker exec $(docker ps -aq) /bin/bash -c 'apt-get update && apt-get -y install sudo';
            if [ "$version" == "16.04" ]; then
                docker exec $(docker ps -aq) /bin/bash -c '/travis_ci/scripts/install-deps-ubuntu.sh';
            fi;
            if [ "$version" == "14.04" ]; then
                docker exec $(docker ps -aq) /bin/bash -c 'sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev;';
            fi;
        fi

    # brew is already installed
    # scripts/install-deps-osx.sh works well
    -   if [ "$os" == "osx" ]; then
            brew install python;
            ./scripts/install-deps-osx.sh;
        fi

script:
    - pwd
    # - docker exec $(docker ps -aq) /bin/bash -c 'pwd'
#  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && make && make install'
