sudo: required

env:
  - distribution: ubuntu
    version: 16.04
    python: 3.5

services:
  - docker

before_install:
  - "docker pull ${distribution}:${version}"

script:
  - "docker build --file=tests/${distribution}-${version}-py${python}.dockerfile ."
