sudo: required

env:
  matrix:
    - DOCKER_IMAGE=ubuntu:16.04

services:
  - docker

language: c++

compiler:
  - gcc

before_install:
  - echo $DOCKER_IMAGE
  - docker pull $DOCKER_IMAGE
  - docker run -d -v $DOCKER_IMAGE

before_script:
  - docker exec $(docker ps -aq) /bin/bash 'scripts/install-deps-ubuntu.sh'

#script:
#  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && make && make install'
