matrix:

  notifications:
    email: false # turn off email notifications for build failure

  language:
    - python
    - cpp

  include:

    # Default environment of MacOS El Capitan
    # compiled using clang shipped with xcode8
    - os: osx
      osx_image: xcode8

    # Default environment of MacOS Sierra
    # compiled using clang shipped with xcode8.3
    - os: osx
      osx_image: xcode8.3

before_install:
  # ISSUE: we may want to use '/scripts/install-deps-ubuntu.sh' in the future.
  # At this moment, travis-ci supports up to ubuntu 14.04 and this environment
  # does not recognize sudo apt-get install libglfw3-dev
  # custom build GLFW3
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev;
      pyenv global 3.6;
      python -m pip install --user --upgrade pip wheel;
      python -V
      ./util/scripts/make-documentation.sh;
    fi
  # scripts/install-deps-osx.sh works well
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pyenv global 3.6;
      python -V;
      ./util/scripts/install-deps-osx.sh;
    fi

script:
  - pwd
  # # Build commands
  # - mkdir build
  # - cd build
  # - cmake ../src/
  # # make -j brings 'virtual memory exhausted: Cannot allocate memory' message
  # # this is presumably due to limited memory space of travis-ci
  # - make
