sudo: required

env:
  - python: 3.5

services:
  - docker

before_install:
  - docker pull ubuntu:16.04

script:
  - docker build .
  - docker-machine ls
  - docker start
  - pwd
  - python -V
  - lsb_release -a
