matrix:

  notifications:
    email: false # turn off email notifications for build failure

  language:
    - python
    - cpp

  include:
    # Default environment of Ubuntu 14.04
    - os: linux
      dist: trusty
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
      env:
         - PYTHON=3.6 CC=gcc-4.8 CXX=g++-4.8

    # Similar environment of Ubuntu 16.04 (gcc 5.4)
    # travis ci only supports Ubuntu 14.04 (trusty) gcc-5 and 6
    # another option is to use docker.
    - os: linux
      dist: trusty
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
      env:
         - PYTHON=3.6 CC=gcc-6 && CXX=g++-6

    # Default environment of MacOS El Capitan
    # compiled using clang shipped with xcode8
    - os: osx
      osx_image: xcode8
      env:
         - PYTHON=3.6

    # Default environment of MacOS Sierra
    # compiled using clang shipped with xcode8.3
    - os: osx
      osx_image: xcode8.3
      env:
         - PYTHON=3.6

before_install:
  # ISSUE: we may want to use '/scripts/install-deps-ubuntu.sh' in the future.
  # At this moment, travis-ci supports up to ubuntu 14.04 and this environment
  # does not recognize sudo apt-get install libglfw3-dev
  # custom build GLFW3
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev;
      git clone https://github.com/glfw/glfw && mkdir build_glfw && cd build_glfw && cmake ../glfw && make -j4 && sudo make install;
      cd ..;
      sudo apt-get install python3.6-dev python3.6-venv;
      python3.6 -m pip install --user --upgrade pip wheel;
      pyenv global system 3.6;
    fi
  # scripts/install-deps-osx.sh works well
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install python3;
      ./scripts/install-deps-osx.sh;
    fi
  # for reference, display cmake and python version
  - python -V
  - cmake --version

script:
  # Build commands
  - mkdir build
  - cd build
