matrix:

    notifications:
        email: false # turn off email notifications for build failure

    sudo: required

    language:
      - python
      - cpp

    include:

        - os: linux
          env:
          - distribution: ubuntu
          - version: 16.04
          - PYTHON=3.6

        - os: linux
          env:
          - distribution: ubuntu
          - version: 14.04
          - PYTHON=3.6

        # Default environment of MacOS El Capitan
        # compiled using clang shipped with xcode8
        - os: osx
          osx_image: xcode8
          env:
            - PYTHON=3.6

        # Default environment of MacOS Sierra
        # compiled using clang shipped with xcode8.3
        - os: osx
          osx_image: xcode8.3
          env:
            - PYTHON=3.6

    services:
        - docker

before_install:

    # Ubuntu systems Docker as travis-ci supports up to ubuntu 14.04.
    # pull and running docker on the background
    # installing dependencies. install sudo as it is not installed by default.
    # Note: Ubuntu 14.04 and this environment does not recognize sudo apt-get install libglfw3-dev
    # Comment in if-statement is now allowed.
    -   if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            docker pull ${distribution}:${version};
            docker run -d -v $(pwd):/travis_ci ${distribution}:${version} /bin/bash -c 'while true; do sleep 1; done';
            docker exec $(docker ps -aq) /bin/bash -c 'apt-get update && apt-get -y install sudo cmake';
            if [ "$version" == "16.04" ]; then
                docker exec $(docker ps -aq) /bin/bash -c '/travis_ci/scripts/install-deps-ubuntu.sh';
            fi;
            if [ "$version" == "14.04" ]; then
                docker exec $(docker ps -aq) /bin/bash -c 'sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev;';
            fi;
        fi

    # brew and cmake is already installed in MacOS images
    # scripts/install-deps-osx.sh works well
    -   if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew upgrade python;
            ./scripts/install-deps-osx.sh;
        fi

script:
    -   if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            docker exec $(docker ps -aq) /bin/bash -c 'cmake --version && python3 -V && pwd';
        fi
    -   if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            cmake --version && python3 -V && pwd;
        fi
    # - docker exec $(docker ps -aq) /bin/bash -c 'pwd'
    # - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && make && make install'
