sudo: required

env:
  matrix:
    - DOCKER_IMAGE=ubuntu:16.04

services:
  - docker

language: c++

compiler:
  - gcc

before_install:
  - echo $DOCKER_IMAGE
  - docker pull $DOCKER_IMAGE
  - docker run -d -v $(pwd):/travis_ci $DOCKER_IMAGE /bin/bash -c 'while true; do sleep 1; done'
  - docker exec $(docker ps -aq) /bin/bash -c 'id'
  - docker exec $(docker ps -aq) /bin/bash -c 'apt-get update && apt-get -y install sudo'

before_script:
  - docker exec $(docker ps -aq) /bin/bash -c 'cd /travis_ci && scripts/install-deps-ubuntu.sh'

script:
  - docker exec $(docker ps -aq) /bin/bash -c 'pwd'
#  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && make && make install'
