notifications:
    email: false # turn off email notifications for build failure

sudo:
    - required
services:
    - docker
before_install:
    - docker pull ubuntu:16.04
script:
    - docker build .
