notifications:
    email: false # turn off email notifications for build failure

sudo: required

env:
    - distribution: ubuntu
      version: 16.04
    - distribution: ubuntu
      version: 14.04

services:
    - docker

language: c++

compiler:
    - gcc

before_install:
    -   if [ "${distribution}" == "ubuntu" ]; then
            # pull and running docker on the background
            docker pull ${distribution}:${version};
            docker run -d -v $(pwd):/travis_ci ${distribution}:${version} /bin/bash -c 'while true; do sleep 1; done';
            # sudo is not installed by default
            docker exec $(docker ps -aq) /bin/bash -c 'apt-get update && apt-get -y install sudo';
        fi
    # installing dependencies.
    -   if [ "${version}" == "16.04" ]; then
            docker exec $(docker ps -aq) /bin/bash -c 'cd /travis_ci && scripts/install-deps-ubuntu.sh';
        fi
    -   if [ "${version}" == "14.04" ]; then
            docker exec $(docker ps -aq) /bin/bash -c 'cd /travis_ci && sudo apt-get install -y xorg-dev libglu1-mesa-dev libgl1-mesa-glx libglew-dev libjsoncpp-dev libeigen3-dev;';
        fi

script:
    - docker exec $(docker ps -aq) /bin/bash -c 'pwd'
#  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && make && make install'
