matrix:

    notifications:
        email: false # turn off email notifications for build failure

    sudo: required

    env:
        matrix:
            - DOCKER_IMAGE=ubuntu:16.04
            - DOCKER_IMAGE=ubuntu:14.04

    services:
        - docker

    language: c++

    compiler:
        - gcc

    before_install:
        - echo $DOCKER_IMAGE
        - docker pull $DOCKER_IMAGE
        # running docker on the background
        - docker run -d -v $(pwd):/travis_ci $DOCKER_IMAGE /bin/bash -c 'while true; do sleep 1; done'
        # run scripts on the background docker
        - docker exec $(docker ps -aq) /bin/bash -c 'id'
        # sudo is not installed by default
        - docker exec $(docker ps -aq) /bin/bash -c 'apt-get update && apt-get -y install sudo'

    before_script:
        # installing dependencies.
        -   if [ "$DOCKER_IMAGE" == "ubuntu:16.04" ]; then
                docker exec $(docker ps -aq) /bin/bash -c 'cd /travis_ci && scripts/install-deps-ubuntu.sh';
            fi

    script:
        - docker exec $(docker ps -aq) /bin/bash -c 'pwd'
    #  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && make && make install'
