notifications:
    email: false # turn off email notifications for build failure

sudo: required

env:
    - distribution: ubuntu
      version: 16.04
    - distribution: ubuntu
      version: 14.04

services:
    - docker

language: c++

compiler:
    - gcc

before_install:
    # pull and running docker on the background
    # installing dependencies. install sudo as it is not installed by default.
    # Note: Ubuntu 14.04 and this environment does not recognize sudo apt-get install libglfw3-dev
    # Comment in if-statement is now allowed.
    -   if [ "${distribution}" == "ubuntu" ]; then
            docker pull ${distribution}:${version};
            docker run -d -v $(pwd):/travis_ci ${distribution}:${version} /bin/bash -c 'while true; do sleep 1; done';
            docker exec $(docker ps -aq) /bin/bash -c 'apt-get update && apt-get -y install sudo';
            docker exec $(docker ps -aq) /bin/bash -c '/travis_ci/scripts/install-deps-ubuntu.sh';            
        fi

script:
    - docker exec $(docker ps -aq) /bin/bash -c 'pwd'
#  - docker exec $(docker ps -aq) /bin/bash -c 'cd /code && make && make install'
